openapi: 3.0.0
info:
  contact:
    email: xld704@gmail.com
    name: Lind Xiao
  description: HTTP port generated from openapi v3
  title: fims-proto vouchers
  version: 1.0.0
servers:
- url: https://{hostname}/vouchers
  variables:
    hostname:
      default: localhost
security:
- bearerAuth: []
paths:
  /:
    get:
      operationId: AllVouchers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trainings'
          description: todo
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error1'
          description: unexpected error
      tags:
      - Voucher
    post:
      operationId: Record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTraining'
        description: todo
        required: true
      responses:
        "204":
          description: todo
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error1'
          description: unexpected error
      tags:
      - Voucher
  /{voucherUUID}:
    get:
      operationId: VoucherForUUID
      parameters:
      - description: todo
        explode: false
        in: path
        name: voucherUUID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: todo
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error1'
          description: unexpected error
      tags:
      - Voucher
    patch:
      operationId: Update
      parameters:
      - explode: false
        in: path
        name: voucherUUID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVoucherCmd'
        description: todo
        required: true
      responses:
        "204":
          description: todo
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error1'
          description: unexpected error
      tags:
      - Voucher
  /{voucherUUID}/audit:
    post:
      operationId: Audit
      parameters:
      - description: todo
        explode: false
        in: path
        name: voucherUUID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditVoucherCmd'
        description: todo
        required: true
      responses:
        "204":
          description: todo
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error1'
          description: unexpected error
      tags:
      - Voucher
  /{voucherUUID}/review:
    post:
      operationId: Review
      parameters:
      - description: todo
        explode: false
        in: path
        name: voucherUUID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewVoucherCmd'
        description: todo
        required: true
      responses:
        "204":
          description: todo
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error1'
          description: unexpected error
      tags:
      - Voucher
components:
  schemas:
    Training:
      example:
        moveRequiresAccept: true
        notes: let's do leg day!
        canBeCancelled: true
        userUuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        proposedTime: 2000-01-23T04:56:07.000+00:00
        time: 2000-01-23T04:56:07.000+00:00
        moveProposedBy: moveProposedBy
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        user: Mariusz Pudzianowski
      properties:
        uuid:
          format: uuid
          type: string
        user:
          example: Mariusz Pudzianowski
          type: string
        userUuid:
          format: uuid
          type: string
        notes:
          example: let's do leg day!
          type: string
        time:
          format: date-time
          type: string
        canBeCancelled:
          type: boolean
        moveRequiresAccept:
          type: boolean
        proposedTime:
          format: date-time
          type: string
        moveProposedBy:
          type: string
      required:
      - canBeCancelled
      - moveRequiresAccept
      - notes
      - time
      - user
      - userUuid
      - uuid
      type: object
    Trainings:
      example:
        trainings:
        - moveRequiresAccept: true
          notes: let's do leg day!
          canBeCancelled: true
          userUuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          proposedTime: 2000-01-23T04:56:07.000+00:00
          time: 2000-01-23T04:56:07.000+00:00
          moveProposedBy: moveProposedBy
          uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          user: Mariusz Pudzianowski
        - moveRequiresAccept: true
          notes: let's do leg day!
          canBeCancelled: true
          userUuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          proposedTime: 2000-01-23T04:56:07.000+00:00
          time: 2000-01-23T04:56:07.000+00:00
          moveProposedBy: moveProposedBy
          uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          user: Mariusz Pudzianowski
      properties:
        trainings:
          items:
            $ref: '#/components/schemas/Training'
          type: array
      required:
      - trainings
      type: object
    PostTraining:
      example:
        notes: let's do leg day!
        time: 2000-01-23T04:56:07.000+00:00
      properties:
        notes:
          example: let's do leg day!
          type: string
        time:
          format: date-time
          type: string
      required:
      - notes
      - time
      type: object
    Error1:
      properties:
        slug:
          type: string
        message:
          type: string
      required:
      - message
      - slug
      type: object
    AuditVoucherCmd:
      example:
        AuditorUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        VoucherUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        VoucherUUID:
          format: uuid
          type: string
        AuditorUUID:
          format: uuid
          type: string
      type: object
    RecordVoucherCmd:
      properties:
        UUID:
          format: uuid
          type: string
        Number:
          minimum: 0
          type: integer
        CreatedAt:
          format: date-time
          type: string
        LineItems:
          items:
            $ref: '#/components/schemas/LineItemCmd'
          type: array
        Debit:
          type: string
        Credit:
          type: string
        CreatorUUID:
          format: uuid
          type: string
      required:
      - time
      type: object
    LineItemCmd:
      example:
        Debit: Debit
        Credit: Credit
        Summary: Summary
        AccountNumber: AccountNumber
      properties:
        Summary:
          type: string
        AccountNumber:
          type: string
        Debit:
          type: string
        Credit:
          type: string
      type: object
    ReviewVoucherCmd:
      example:
        ReviewerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        VoucherUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        VoucherUUID:
          format: uuid
          type: string
        ReviewerUUID:
          format: uuid
          type: string
      type: object
    UpdateVoucherCmd:
      example:
        LineItems:
        - Debit: Debit
          Credit: Credit
          Summary: Summary
          AccountNumber: AccountNumber
        - Debit: Debit
          Credit: Credit
          Summary: Summary
          AccountNumber: AccountNumber
        VoucherUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        VoucherUUID:
          format: uuid
          type: string
        LineItems:
          items:
            $ref: '#/components/schemas/LineItemCmd'
          type: array
      type: object
    LineItemQry:
      properties:
        Summary:
          type: string
        AccountNumber:
          type: string
        Debit:
          type: string
        Credit:
          type: string
      type: object
    VoucherQry:
      properties:
        UUID:
          format: uuid
          type: string
        Number:
          minimum: 0
          type: integer
        CreatedAt:
          format: date-time
          type: string
        AttachmentQuantity:
          minimum: 0
          type: integer
        LineItems:
          items:
            $ref: '#/components/schemas/LineItemQry'
          type: array
        Debit:
          type: string
        Credit:
          type: string
        CreatorUUID:
          format: uuid
          type: string
        ReviewerUUID:
          format: uuid
          type: string
        IsReviewed:
          type: boolean
        AuditorUUID:
          format: uuid
          type: string
        IsAudited:
          type: boolean
      required:
      - time
      type: object
    VouchersQry:
      items:
        $ref: '#/components/schemas/VoucherQry'
      type: array
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
